# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hotel_management_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
